"""san type for employee

Revision ID: e7fc12be2b0c
Revises: 427c2c01b42c
Create Date: 2025-05-05 15:55:18.439509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7fc12be2b0c'
down_revision: Union[str, None] = '427c2c01b42c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees',
                  sa.Column('sanitary_type', postgresql.ENUM('main', 'car', 'tractor', name='sanitary_type_enum'),
                            nullable=False, server_default="main"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'sanitary_type')
    # ### end Alembic commands ###
