"""sanitary breaks type

Revision ID: 83ec2b242bd5
Revises: 37c8bc4a7213
Create Date: 2025-04-11 21:33:09.716782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83ec2b242bd5'
down_revision: Union[str, None] = '37c8bc4a7213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_column('sanitary_breaks', 'sanitary_type')
    op.execute('DROP TYPE sanitary_type_enum')
    op.execute("CREATE TYPE sanitary_type_enum AS ENUM ('main', 'car', 'tractor')")
    op.add_column('sanitary_breaks',
                  sa.Column('sanitary_type', postgresql.ENUM('main', 'car', 'tractor', name='sanitary_type_enum'), nullable=False))

    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sanitary_breaks', 'sanitary_type')
    op.execute('DROP TYPE sanitary_type_enum')
    op.execute("CREATE TYPE sanitary_type_enum AS ENUM ('employee', 'car', 'tractor')")
    op.add_column('sanitary_breaks',
                  sa.Column('sanitary_type', postgresql.ENUM('employee', 'car', 'tractor', name='sanitary_type_enum'),
                            nullable=False))
    # ### end Alembic commands ###
