"""visit history enum

Revision ID: 12f24aa2ea4b
Revises: b1f29d5583c1
Create Date: 2025-04-07 23:57:50.244585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f24aa2ea4b'
down_revision: Union[str, None] = 'b1f29d5583c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_column('visit_history', 'status')
    op.execute('DROP TYPE visit_status_enum')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
