"""san table in employee edit

Revision ID: 13980f5da0d9
Revises: e97410610ebf
Create Date: 2025-05-05 17:03:37.051982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13980f5da0d9'
down_revision: Union[str, None] = 'e97410610ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'sanitary_table',
                    existing_type=postgresql.ENUM('main', 'car', 'tractor', name='sanitary_type_enum'),
                    nullable=True, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'sanitary_table',
                    existing_type=postgresql.ENUM('main', 'car', 'tractor', name='sanitary_type_enum'),
                    nullable=True,
                    existing_server_default=sa.text("'main'::sanitary_type_enum"))
    # ### end Alembic commands ###
