"""san table in employee edit

Revision ID: 6fd766c2ff19
Revises: 13980f5da0d9
Create Date: 2025-05-05 17:10:30.231792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fd766c2ff19'
down_revision: Union[str, None] = '13980f5da0d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'sanitary_table',
               existing_type=postgresql.ENUM('main', 'car', 'tractor', name='sanitary_type_enum'),
               nullable=False, server_default="main")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'sanitary_table',
               existing_type=postgresql.ENUM('main', 'car', 'tractor', name='sanitary_type_enum'),
               nullable=True)
    # ### end Alembic commands ###
