"""default san type for employee

Revision ID: 20041c8bb3a4
Revises: e7fc12be2b0c
Create Date: 2025-05-05 15:57:56.512908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20041c8bb3a4'
down_revision: Union[str, None] = 'e7fc12be2b0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'sanitary_type',
               existing_type=postgresql.ENUM('main', 'car', 'tractor', name='sanitary_type_enum'),
               nullable=False, server_default="main")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'sanitary_type',
               existing_type=postgresql.ENUM('main', 'car', 'tractor', name='sanitary_type_enum'),
               nullable=True)
    # ### end Alembic commands ###
