"""san table

Revision ID: e97410610ebf
Revises: cdb5acbdecfc
Create Date: 2025-05-05 16:33:13.712183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e97410610ebf'
down_revision: Union[str, None] = 'cdb5acbdecfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'sanitary_table',
               existing_type=postgresql.ENUM('main', 'car', 'tractor', name='sanitary_type_enum'),
               nullable=True,
               existing_server_default=sa.text("'main'::sanitary_type_enum"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'sanitary_table',
               existing_type=postgresql.ENUM('main', 'car', 'tractor', name='sanitary_type_enum'),
               nullable=False,
               existing_server_default=sa.text("'main'::sanitary_type_enum"))
    # ### end Alembic commands ###
