"""groups

Revision ID: 9894437fd6cc
Revises: 7203c6be176b
Create Date: 2025-04-06 23:30:37.106118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9894437fd6cc'
down_revision: Union[str, None] = '7203c6be176b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('groups', 'groups')
    op.alter_column('employees', 'position_id', new_column_name='group_id')
    # op.create_table('groups',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('title', sa.String(length=100), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('id'),
    # sa.UniqueConstraint('title')
    # )
    #op.drop_table('groups')
    # op.add_column('employees', sa.Column('group_id', sa.Integer(), nullable=True))
    # op.drop_constraint('employees_position_id_fkey', 'employees', type_='foreignkey')
    # op.create_foreign_key(None, 'employees', 'groups', ['group_id'], ['id'])
    # op.drop_column('employees', 'position_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key('employees_position_id_fkey', 'employees', 'groups', ['position_id'], ['id'])
    op.drop_column('employees', 'group_id')
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='positions_pkey'),
    sa.UniqueConstraint('id', name='positions_id_key'),
    sa.UniqueConstraint('title', name='positions_title_key')
    )
    op.drop_table('groups')
    # ### end Alembic commands ###
