"""status object

Revision ID: c93a6be27268
Revises: 8dc277b6fff1
Create Date: 2025-04-08 22:09:09.802749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c93a6be27268'
down_revision: Union[str, None] = '8dc277b6fff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE object_status_enum AS ENUM ('open', 'close')")
    op.add_column('objects', sa.Column('status', postgresql.ENUM('open', 'close', name='object_status_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'status')
    op.execute('DROP TYPE object_status_enum')
    # ### end Alembic commands ###
