"""Order-product table

Revision ID: 5a0cd7488ed7
Revises: 1ebc0cd3e026
Create Date: 2025-03-25 18:24:23.972653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a0cd7488ed7'
down_revision: Union[str, None] = '1ebc0cd3e026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_position_association', 'employee_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('employee_position_association', 'position_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('employee_position_association_employee_id_position_id_key', 'employee_position_association', type_='unique')
    op.create_unique_constraint(None, 'positions', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'positions', type_='unique')
    op.create_unique_constraint('employee_position_association_employee_id_position_id_key', 'employee_position_association', ['employee_id', 'position_id'])
    op.alter_column('employee_position_association', 'position_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employee_position_association', 'employee_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
