"""Order-product table

Revision ID: e8f405b4f8d0
Revises: 5a0cd7488ed7
Create Date: 2025-03-25 18:28:31.884729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f405b4f8d0'
down_revision: Union[str, None] = '5a0cd7488ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_position_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_position_association',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='employee_position_association_employee_id_fkey'),
    sa.ForeignKeyConstraint(['position_id'], ['groups.id'], name='employee_position_association_position_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='employee_position_association_pkey')
    )
    # ### end Alembic commands ###
