"""edit sanitary breaks

Revision ID: 85b773f9ab7e
Revises: 83ec2b242bd5
Create Date: 2025-04-16 21:52:42.098782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85b773f9ab7e'
down_revision: Union[str, None] = '83ec2b242bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sanitary_changes_sanitary_object_id_fkey', 'sanitary_changes', type_='foreignkey')
    op.alter_column('sanitary_changes', 'sanitary_object_id', new_column_name='sanitary_break_id')
    op.create_foreign_key(None, 'sanitary_changes', 'sanitary_breaks', ['sanitary_break_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(None, 'sanitary_changes', type_='foreignkey')

    # Переименовываем колонку обратно
    op.alter_column('sanitary_changes', 'sanitary_break_id', new_column_name='sanitary_object_id')

    # Восстанавливаем внешний ключ на sanitary_objects (если он туда указывал)
    op.create_foreign_key(
        'sanitary_changes_sanitary_object_id_fkey',
        'sanitary_changes', 'sanitary_objects',
        ['sanitary_object_id'], ['id']
    )
