"""visit history enum

Revision ID: 2844f23b61d1
Revises: 12f24aa2ea4b
Create Date: 2025-04-07 23:58:30.221827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2844f23b61d1'
down_revision: Union[str, None] = '12f24aa2ea4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE visit_status_enum AS ENUM ('Успешно', 'Ошибка')")
    op.add_column('visit_history', sa.Column('status', postgresql.ENUM('Успешно', 'Ошибка', name='visit_status_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit_history', 'status')
    # ### end Alembic commands ###
