"""Employee update groups

Revision ID: 33b2145856ed
Revises: e8f405b4f8d0
Create Date: 2025-03-25 18:32:59.880340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b2145856ed'
down_revision: Union[str, None] = 'e8f405b4f8d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'groups', ['position_id'], ['id'])
    op.drop_column('employees', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('position', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'position_id')
    # ### end Alembic commands ###
