"""san table

Revision ID: cdb5acbdecfc
Revises: 9ea037a716bd
Create Date: 2025-05-05 16:31:22.320738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdb5acbdecfc'
down_revision: Union[str, None] = '9ea037a716bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('sanitary_table', postgresql.ENUM('main', 'car', 'tractor', name='sanitary_type_enum'), server_default='main', nullable=False))
    op.drop_column('employees', 'sanitary_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('sanitary_type', postgresql.ENUM('main', 'car', 'tractor', name='sanitary_type_enum'), server_default=sa.text("'main'::sanitary_type_enum"), autoincrement=False, nullable=False))
    op.drop_column('employees', 'sanitary_table')
    # ### end Alembic commands ###
