"""visit history enum

Revision ID: 8dc277b6fff1
Revises: 2844f23b61d1
Create Date: 2025-04-08 00:02:08.132340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dc277b6fff1'
down_revision: Union[str, None] = '2844f23b61d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_column('visit_history', 'status')
    op.execute('DROP TYPE visit_status_enum')
    op.execute("CREATE TYPE visit_status_enum AS ENUM ('success', 'error')")
    op.add_column('visit_history', sa.Column('status', postgresql.ENUM('success', 'error', name='visit_status_enum'), nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
