"""add default value object

Revision ID: 7230508b2110
Revises: ded512c544fc
Create Date: 2025-05-08 14:43:44.740687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7230508b2110'
down_revision: Union[str, None] = 'ded512c544fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('objects', 'status',
                    existing_type=postgresql.ENUM('open', 'close', name='object_status_enum'),
                    nullable=False, server_default="open")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('objects', 'status',
                    existing_type=postgresql.ENUM('open', 'close', name='object_status_enum'),
                    nullable=False, server_default=None)
    # ### end Alembic commands ###
