"""sanitary breaks type

Revision ID: 37c8bc4a7213
Revises: 9b6209fa4405
Create Date: 2025-04-11 20:42:41.972130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37c8bc4a7213'
down_revision: Union[str, None] = '9b6209fa4405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sanitary_breaks', ['id'])
    op.create_unique_constraint(None, 'sanitary_changes', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sanitary_changes', type_='unique')
    op.drop_constraint(None, 'sanitary_breaks', type_='unique')
    # ### end Alembic commands ###
