"""visit history add was_reported_missing_exit

Revision ID: ded512c544fc
Revises: 6fd766c2ff19
Create Date: 2025-05-05 17:30:13.207323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded512c544fc'
down_revision: Union[str, None] = '6fd766c2ff19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit_history', sa.Column('was_reported_missing_exit', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit_history', 'was_reported_missing_exit')
    # ### end Alembic commands ###
